### ISSUE TITLE
body undefined at observer.observe(...) time

### ISSUE THREAD

**Issue by Qard** [shama/on-load#14]
I'm using on-load through choo and am getting "Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'."

It would seem `document.body` does not existing yet when `observer.observe(...)` tries to run. If I wrap the observe call in a `window.onload = () { ... }` it works fine.

**Comment by shama** [comment]
When would one need to use this before the document has loaded?

**Comment by Qard** [comment]
My use is with rollup. To get the tree-shaking goodness of rollup, modules need to be loaded using `import` statements, which happen at the top level and thus end up loading `on-load` before the document is ready.

**Comment by hdriqi** [comment]
I got this error too, and then i change on-load module:
 ```
 if(document.body){
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeOldValue: true,
      attributeFilter: [KEY_ATTR]
    })
  }
```
the error is gone but does it affect the module functionality??

btw, this error happened because using webpack and import statement. I think webpack is trying to run the module before the DOM loaded.

**Comment by yoshuawuyts** [comment]
You could perhaps rely on https://github.com/bendrucker/document-ready ?
Not sure what webpack does, but that way you can at least be sure certain
things don't happen on the DOM before others (:

**Comment by hdriqi** [comment]
@yoshuawuyts thanks a lot dude!
