### ISSUE TITLE
Not being called when toggling between two elements of the same tagName

### ISSUE THREAD

**Issue by timwis** [shama/on-load#5]
Per [yoshuawuyts/choo#1](https://github.com/yoshuawuyts/choo/issues/1#issuecomment-228577390):

> hopefully I'm just doing it wrong but I was just trying to implement `on-load` and ran into unexpected behaviour with it. Perhaps I'm misunderstanding? Here's a [simple test case](https://gist.github.com/timwis/ecf6fe13ccb51fb1fd093b854be78a45). Shouldn't that work?
> 
> It seems like the second page doesn't trigger `onload` because it uses the same type of parent container (`<div>`). Even if you give that `<div>` different `id` or `class`, it doesn't trigger the second view. Only if you use a different element type (like `<section>`).

@yoshuawuyts suggested it may be because of [this](https://github.com/shama/on-load/blob/master/index.js#L15) not being cleaned up. Any advice?

**Comment by shama** [comment]
Oh interesting. It looks like morphdom doesn't add/remove that node so the mutation observer never fires. It only changes the attribute in the DOM.

I can fix that by also observing the `data-onloadid` attribute and when one changes into another, fire the `onunload` and `onload` for each respectively.

**Comment by shama** [comment]
@timwis Ok give `2.2.0` a go. It now watches `data-onloadid` attribute changes in case the node doesn't change but the attribute did. It has some perf improvements too.

**Comment by timwis** [comment]
woohoo! Looks like the above test case is working as expected now. Thanks for the quick resolution, @shama!
