### ISSUE TITLE
Pass el to onload callback

### ISSUE THREAD

**Issue by timwis** [shama/on-load#7]
In bel, @yoshuawuyts [suggested](https://github.com/shama/bel/issues/30#issuecomment-228212855):

> Might be worth considering to pass the enclosing element as the first argument to the callback for onload so that any stuff like d3 can just attach itself to the node instead of having to do some odd hoop jumping to find the node it should append itself to.

I see [you incorporated that](https://github.com/shama/bel/blob/master/index.js#L62) - thanks! Makes things a lot easier. I wonder, though, whether it fits better in `on-load`? So that both `onload(el, on)` and `<div onload=${on}>` callbacks have the same signature? If so, I'm happy to throw the PR together, but wanted to ask whether there was a reason behind it first.

Thanks again!

**Comment by shama** [comment]
The main reason is so I don't have to keep a reference to the element around (as we don't get the old element onunload). But agree having the same signature would be nice and would take a patch for it. Thanks!
